apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: clusterroles-session-rules
parameters:
- name: NAME_PREFIX
  value: ""
  required: false
- name: WORKSHOP_NAME
  value: ""
  required: true
- name: SPAWNER_NAMESPACE
  value: ""
  required: true
- name: SPAWNER_MODE
  value: "learning-portal"
  required: true
objects:
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRole
  metadata:
    name: ${NAME_PREFIX}${WORKSHOP_NAME}-session-rules
    labels:
      app: ${NAME_PREFIX}${WORKSHOP_NAME}
      spawner: ${SPAWNER_MODE}
      class: spawner
  rules:
  - apiGroups:
    - ""
    - "cr.client-go.k8s.io"
    resources:
    - pgclusters
    - pgbackups
    - pgpolicies
    - pgreplicas
    - pgtasks
    - pgupgrades
    verbs:
    - get
    - list
    - watch
