apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: clusterroles-spawner-rules
parameters:
- name: NAME_PREFIX
  value: ""
  required: false
- name: WORKSHOP_NAME
  value: ""
  required: true
- name: SPAWNER_NAMESPACE
  value: ""
  required: true
- name: SPAWNER_MODE
  value: "learning-portal"
  required: true
objects:
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRole
  metadata:
    name: ${NAME_PREFIX}${WORKSHOP_NAME}-spawner-rules
    labels:
      app: ${NAME_PREFIX}${WORKSHOP_NAME}
      spawner: ${SPAWNER_MODE}
      class: spawner
  rules:
  - apiGroups:
    - ""
    - authorization.openshift.io
    - rbac.authorization.k8s.io
    resourceNames:
    - pgo-role
    - pgo-backrest-role
    resources:
    - clusterroles
    - roles
    verbs:
    - bind
  - apiGroups:
    - ""
    resources:
    - configmaps
    - endpoints
    - events
    - persistentvolumeclaims
    - pods
    - secrets
    - services
    verbs:
    - "*"
  - apiGroups:
    - "apps"
    - "extensions"
    resources:
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
    verbs:
    - "*"
  - apiGroups:
    - "batch"
    resources:
    - jobs
    verbs:
    - "*"
  - apiGroups:
    - ""
    - "cr.client-go.k8s.io"
    resources:
    - pgclusters
    - pgbackups
    - pgpolicies
    - pgreplicas
    - pgtasks
    - pgupgrades
    verbs:
    - "*"
